package com.bhz.pojo;



/**
 * TbBaoJingSubMerge generated by MyEclipse - Hibernate Tools
 */

public class TbBaoJingSubMerge  implements java.io.Serializable {


    // Fields    

     private Integer subId;
     private String mainId;
     private String bdCode;
     private String bhzCode;
     private String phbQd;
     private String sendType;
     private String mobile;
     private String mobile_bdCode;
	 private String downValue;
     private String upValue;


    // Constructors

    /** default constructor */
    public TbBaoJingSubMerge() {
    }

	/** minimal constructor */
    public TbBaoJingSubMerge(String mainId) {
        this.mainId = mainId;
    }
    
    /** full constructor */
    public TbBaoJingSubMerge(String mainId, String bdCode, String bhzCode, String phbQd, String sendType, String mobile, String mobile_bdCode, String downValue, String upValue) {
        this.mainId = mainId;
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.phbQd = phbQd;
        this.sendType = sendType;
        this.mobile = mobile;
        this.mobile_bdCode = mobile_bdCode;
        this.downValue = downValue;
        this.upValue = upValue;
    }

   
    // Property accessors

    public Integer getSubId() {
        return this.subId;
    }
    
    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    public String getMainId() {
        return this.mainId;
    }
    
    public void setMainId(String mainId) {
        this.mainId = mainId;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getBhzCode() {
        return this.bhzCode;
    }
    
    public void setBhzCode(String bhzCode) {
        this.bhzCode = bhzCode;
    }

    public String getPhbQd() {
        return this.phbQd;
    }
    
    public void setPhbQd(String phbQd) {
        this.phbQd = phbQd;
    }

    public String getSendType() {
        return this.sendType;
    }
    
    public void setSendType(String sendType) {
        this.sendType = sendType;
    }

    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    public String getMobile_bdCode() {
		return mobile_bdCode;
	}

	public void setMobile_bdCode(String mobile_bdCode) {
		this.mobile_bdCode = mobile_bdCode;
	}

    public String getDownValue() {
        return this.downValue;
    }
    
    public void setDownValue(String downValue) {
        this.downValue = downValue;
    }

    public String getUpValue() {
        return this.upValue;
    }
    
    public void setUpValue(String upValue) {
        this.upValue = upValue;
    }

}