package com.bhz.pojo;



/**
 * TbBaseAuthority generated by MyEclipse - Hibernate Tools
 */

public class TbBaseAuthority  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String funCode;
     private String funName;
     private String parentCode;
     private Integer leve;


    // Constructors

    /** default constructor */
    public TbBaseAuthority() {
    }

    
    /** full constructor */
    public TbBaseAuthority(String funCode, String funName, String parentCode, Integer leve) {
        this.funCode = funCode;
        this.funName = funName;
        this.parentCode = parentCode;
        this.leve = leve;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getFunCode() {
        return this.funCode;
    }
    
    public void setFunCode(String funCode) {
        this.funCode = funCode;
    }

    public String getFunName() {
        return this.funName;
    }
    
    public void setFunName(String funName) {
        this.funName = funName;
    }

    public String getParentCode() {
        return this.parentCode;
    }
    
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    public Integer getLeve() {
        return this.leve;
    }
    
    public void setLeve(Integer leve) {
        this.leve = leve;
    }
   








}