package com.bhz.pojo;



/**
 * TbBaoJingBase generated by MyEclipse - Hibernate Tools
 */

public class TbBaoJingBase  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String clName;
     private String isBaojing;
     private String msgContent;
     private String downValueCj;
     private String upValueCj;
     private String downValueZj;
     private String upValueZj;
     private String downValueGj;
     private String upValueGj;


    // Constructors

    /** default constructor */
    public TbBaoJingBase() {
    }

    
    /** full constructor */
    public TbBaoJingBase(String clName, String isBaojing, String msgContent, String downValueCj, String upValueCj, String downValueZj, String upValueZj, String downValueGj, String upValueGj) {
        this.clName = clName;
        this.isBaojing = isBaojing;
        this.msgContent = msgContent;
        this.downValueCj = downValueCj;
        this.upValueCj = upValueCj;
        this.downValueZj = downValueZj;
        this.upValueZj = upValueZj;
        this.downValueGj = downValueGj;
        this.upValueGj = upValueGj;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getClName() {
        return this.clName;
    }
    
    public void setClName(String clName) {
        this.clName = clName;
    }

    public String getIsBaojing() {
        return this.isBaojing;
    }
    
    public void setIsBaojing(String isBaojing) {
        this.isBaojing = isBaojing;
    }

    public String getMsgContent() {
        return this.msgContent;
    }
    
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }

    public String getDownValueCj() {
        return this.downValueCj;
    }
    
    public void setDownValueCj(String downValueCj) {
        this.downValueCj = downValueCj;
    }

    public String getUpValueCj() {
        return this.upValueCj;
    }
    
    public void setUpValueCj(String upValueCj) {
        this.upValueCj = upValueCj;
    }

    public String getDownValueZj() {
        return this.downValueZj;
    }
    
    public void setDownValueZj(String downValueZj) {
        this.downValueZj = downValueZj;
    }

    public String getUpValueZj() {
        return this.upValueZj;
    }
    
    public void setUpValueZj(String upValueZj) {
        this.upValueZj = upValueZj;
    }

    public String getDownValueGj() {
        return this.downValueGj;
    }
    
    public void setDownValueGj(String downValueGj) {
        this.downValueGj = downValueGj;
    }

    public String getUpValueGj() {
        return this.upValueGj;
    }
    
    public void setUpValueGj(String upValueGj) {
        this.upValueGj = upValueGj;
    }
   








}