package com.bhz.pojo;



/**
 * TbBaoJingPersonBase generated by MyEclipse - Hibernate Tools
 */

public class TbBaoJingPersonBase  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bdCode;
     private String bhzCode;
     private String userMobileCj;
     private String userMobileZj;
	 private String userMobileGj;
	 private String mobileCJ_bdCode;
	 private String mobileZJ_bdCode;
	 private String mobileGJ_bdCode;

    // Constructors

	/** default constructor */
    public TbBaoJingPersonBase() {
    }

    
    /** full constructor */
    public TbBaoJingPersonBase(String bdCode, String bhzCode, String userMobileCj, String userMobileZj, String userMobileGj, String mobileCJ_bdCode, String mobileZJ_bdCode, String mobileGJ_bdCode) {
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.userMobileCj = userMobileCj;
        this.userMobileZj = userMobileZj;
        this.userMobileGj = userMobileGj;
        this.mobileCJ_bdCode = mobileCJ_bdCode;
        this.mobileZJ_bdCode = mobileZJ_bdCode;
        this.mobileGJ_bdCode = mobileGJ_bdCode;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getBhzCode() {
        return this.bhzCode;
    }
    
    public void setBhzCode(String bhzCode) {
        this.bhzCode = bhzCode;
    }

    public String getUserMobileCj() {
        return this.userMobileCj;
    }
    
    public void setUserMobileCj(String userMobileCj) {
        this.userMobileCj = userMobileCj;
    }
   
    public String getUserMobileZj() {
		return this.userMobileZj;
	}

	public void setUserMobileZj(String userMobileZj) {
		this.userMobileZj = userMobileZj;
	}

	public String getUserMobileGj() {
		return userMobileGj;
	}

	public void setUserMobileGj(String userMobileGj) {
		this.userMobileGj = userMobileGj;
	}
	
    public String getMobileCJ_bdCode() {
		return mobileCJ_bdCode;
	}

	public void setMobileCJ_bdCode(String mobileCJ_bdCode) {
		this.mobileCJ_bdCode = mobileCJ_bdCode;
	}

	public String getMobileZJ_bdCode() {
		return mobileZJ_bdCode;
	}

	public void setMobileZJ_bdCode(String mobileZJ_bdCode) {
		this.mobileZJ_bdCode = mobileZJ_bdCode;
	}

	public String getMobileGJ_bdCode() {
		return mobileGJ_bdCode;
	}

	public void setMobileGJ_bdCode(String mobileGJ_bdCode) {
		this.mobileGJ_bdCode = mobileGJ_bdCode;
	}

}