package com.bhz.pojo;

import java.util.Date;

/**
 * TbBase generated by MyEclipse - Hibernate Tools
 */

public class TbBase implements java.io.Serializable {

	// Fields

	private Integer id;

	private String groupId; // 组ID

	private String m1; // 配合比类型 0:理论 1:实际 2:施工

	private String m2; // 标段编号

	private String m3; // 工程名称

	private String m4; // 出料时间

	private String m5; // 浇筑部位

	private String m6; // 拌合站编号

	private String m7; // 配合比编号

	private String m8; // 理论配合比 现使用作为 配合比强度
	
	private String m9;	//搅拌时间 单位:s
	
	private Double m10;	//方量

	private String a1;

	private String a2;

	private String a3;

	private String a4;

	private String a5;

	private String a6;

	private String a7;

	private String a8;

	private String a9;

	private String a10;

	private String a11;

	private String a12;

	private String a13;

	private String a14;

	private String a15;

	private String a16;

	private String a17;

	private String a18;

	private String a19;

	private String a20;
	
	private String isShow;	//1为不显示不统计的非法数据
	
	private String bjType;	//报警类型

	private String bhzCarNum;//拌合站车牌号

	private String bhzCarOrder;//拌合站车次

	private Float bhzTotalQt;//总方量

	private String bhzOperator;//操作手

	private String bhzCarBjType;//车次报警类型

	// Constructors

	/** default constructor */
	public TbBase() {
	}

	/** full constructor */
	public TbBase(String groupId, String m1, String m2, String m3, String m4,
			String m5, String m6, String m7, String m8, String m9, Double m10, 
			String a1,String a2, String a3, String a4, String a5, 
			String a6, String a7, String a8, String a9, String a10, String a11, 
			String a12, String a13,String a14, String a15, String a16, String a17, 
			String a18,String a19, String a20, String isShow) {
		this.groupId = groupId;
		this.m1 = m1;
		this.m2 = m2;
		this.m3 = m3;
		this.m4 = m4;
		this.m5 = m5;
		this.m6 = m6;
		this.m7 = m7;
		this.m8 = m8;
		this.m9 = m9;
		this.m10 = m10;
		this.a1 = a1;
		this.a2 = a2;
		this.a3 = a3;
		this.a4 = a4;
		this.a5 = a5;
		this.a6 = a6;
		this.a7 = a7;
		this.a8 = a8;
		this.a9 = a9;
		this.a10 = a10;
		this.a11 = a11;
		this.a12 = a12;
		this.a13 = a13;
		this.a14 = a14;
		this.a15 = a15;
		this.a16 = a16;
		this.a17 = a17;
		this.a18 = a18;
		this.a19 = a19;
		this.a20 = a20;
		this.isShow = isShow;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getM1() {
		return this.m1;
	}

	public void setM1(String m1) {
		this.m1 = m1;
	}

	public String getM2() {
		return this.m2;
	}

	public void setM2(String m2) {
		this.m2 = m2;
	}

	public String getM3() {
		return this.m3;
	}

	public void setM3(String m3) {
		this.m3 = m3;
	}

	public String getM4() {
		return m4;
	}

	public void setM4(String m4) {
		this.m4 = m4;
	}

	public String getM5() {
		return this.m5;
	}

	public void setM5(String m5) {
		this.m5 = m5;
	}

	public String getM6() {
		return this.m6;
	}

	public void setM6(String m6) {
		this.m6 = m6;
	}

	public String getM7() {
		return this.m7;
	}

	public void setM7(String m7) {
		this.m7 = m7;
	}

	public String getM8() {
		return this.m8;
	}

	public void setM8(String m8) {
		this.m8 = m8;
	}

	public String getA1() {
		return this.a1;
	}

	public void setA1(String a1) {
		this.a1 = a1;
	}

	public String getA2() {
		return this.a2;
	}

	public void setA2(String a2) {
		this.a2 = a2;
	}

	public String getA3() {
		return this.a3;
	}

	public void setA3(String a3) {
		this.a3 = a3;
	}

	public String getA4() {
		return this.a4;
	}

	public void setA4(String a4) {
		this.a4 = a4;
	}

	public String getA5() {
		return this.a5;
	}

	public void setA5(String a5) {
		this.a5 = a5;
	}

	public String getA6() {
		return this.a6;
	}

	public void setA6(String a6) {
		this.a6 = a6;
	}

	public String getA7() {
		return this.a7;
	}

	public void setA7(String a7) {
		this.a7 = a7;
	}

	public String getA8() {
		return this.a8;
	}

	public void setA8(String a8) {
		this.a8 = a8;
	}

	public String getA9() {
		return this.a9;
	}

	public void setA9(String a9) {
		this.a9 = a9;
	}

	public String getA10() {
		return this.a10;
	}

	public void setA10(String a10) {
		this.a10 = a10;
	}

	public String getA11() {
		return this.a11;
	}

	public void setA11(String a11) {
		this.a11 = a11;
	}

	public String getA12() {
		return this.a12;
	}

	public void setA12(String a12) {
		this.a12 = a12;
	}

	public String getA13() {
		return this.a13;
	}

	public void setA13(String a13) {
		this.a13 = a13;
	}

	public String getA14() {
		return this.a14;
	}

	public void setA14(String a14) {
		this.a14 = a14;
	}

	public String getA15() {
		return this.a15;
	}

	public void setA15(String a15) {
		this.a15 = a15;
	}

	public String getA16() {
		return this.a16;
	}

	public void setA16(String a16) {
		this.a16 = a16;
	}

	public String getA17() {
		return this.a17;
	}

	public void setA17(String a17) {
		this.a17 = a17;
	}

	public String getA18() {
		return this.a18;
	}

	public void setA18(String a18) {
		this.a18 = a18;
	}

	public String getA19() {
		return this.a19;
	}

	public void setA19(String a19) {
		this.a19 = a19;
	}

	public String getA20() {
		return this.a20;
	}

	public void setA20(String a20) {
		this.a20 = a20;
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getM9() {
		return m9;
	}

	public void setM9(String m9) {
		this.m9 = m9;
	}

	public Double getM10() {
		return m10;
	}

	public void setM10(Double m10) {
		this.m10 = m10;
	}

	public String getIsShow() {
		return isShow;
	}

	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}

	public String getBjType() {
		return bjType;
	}

	public void setBjType(String bjType) {
		this.bjType = bjType;
	}

	public String getBhzCarNum() {
		return bhzCarNum;
	}

	public void setBhzCarNum(String bhzCarNum) {
		this.bhzCarNum = bhzCarNum;
	}

	public String getBhzCarOrder() {
		return bhzCarOrder;
	}

	public void setBhzCarOrder(String bhzCarOrder) {
		this.bhzCarOrder = bhzCarOrder;
	}

	public Float getBhzTotalQt() {
		return bhzTotalQt;
	}

	public void setBhzTotalQt(Float bhzTotalQt) {
		this.bhzTotalQt = bhzTotalQt;
	}

	public String getBhzOperator() {
		return bhzOperator;
	}

	public void setBhzOperator(String bhzOperator) {
		this.bhzOperator = bhzOperator;
	}

	public String getBhzCarBjType() {
		return bhzCarBjType;
	}

	public void setBhzCarBjType(String bhzCarBjType) {
		this.bhzCarBjType = bhzCarBjType;
	}
}