package com.bhz.pojo;



/**
 * TbBd generated by MyEclipse - Hibernate Tools
 */

public class TbBd  implements java.io.Serializable {


    // Fields    

     private String bdCode;
     private String bdName;
     private Integer orderNum;
     private String ext1;


    // Constructors

    /** default constructor */
    public TbBd() {
    }

	/** minimal constructor */
    public TbBd(String bdCode) {
        this.bdCode = bdCode;
    }
    
    /** full constructor */
    public TbBd(String bdCode, String bdName, Integer orderNum, String ext1) {
        this.bdCode = bdCode;
        this.bdName = bdName;
        this.orderNum = orderNum;
        this.ext1 = ext1;
    }

   
    // Property accessors

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getBdName() {
        return this.bdName;
    }
    
    public void setBdName(String bdName) {
        this.bdName = bdName;
    }

    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
   








}