package com.bhz.pojo;



/**
 * TbDesignPhb generated by MyEclipse - Hibernate Tools
 */

public class TbDesignPhb  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bdCode;
     private String bhzCode;
     private String intensityGrade;
     private String a1;
     private String a2;
     private String a3;
     private String a4;
     private String a5;
     private String a6;
     private String a7;
     private String a8;
     private String a9;
     private String a10;
     private String a11;
     private String a12;
     private String a13;
     private String a14;
     private String a15;
     private String a16;
     private String a17;
     private String a18;
     private String a19;
     private String a20;


    // Constructors

    /** default constructor */
    public TbDesignPhb() {
    }

    
    /** full constructor */
    public TbDesignPhb(String bdCode, String bhzCode, String intensityGrade, String a1, String a2, String a3, String a4, String a5, String a6, String a7, String a8, String a9, String a10, String a11, String a12, String a13, String a14, String a15, String a16, String a17, String a18, String a19, String a20) {
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.intensityGrade = intensityGrade;
        this.a1 = a1;
        this.a2 = a2;
        this.a3 = a3;
        this.a4 = a4;
        this.a5 = a5;
        this.a6 = a6;
        this.a7 = a7;
        this.a8 = a8;
        this.a9 = a9;
        this.a10 = a10;
        this.a11 = a11;
        this.a12 = a12;
        this.a13 = a13;
        this.a14 = a14;
        this.a15 = a15;
        this.a16 = a16;
        this.a17 = a17;
        this.a18 = a18;
        this.a19 = a19;
        this.a20 = a20;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getBhzCode() {
        return this.bhzCode;
    }
    
    public void setBhzCode(String bhzCode) {
        this.bhzCode = bhzCode;
    }

    public String getIntensityGrade() {
        return this.intensityGrade;
    }
    
    public void setIntensityGrade(String intensityGrade) {
        this.intensityGrade = intensityGrade;
    }

    public String getA1() {
        return this.a1;
    }
    
    public void setA1(String a1) {
        this.a1 = a1;
    }

    public String getA2() {
        return this.a2;
    }
    
    public void setA2(String a2) {
        this.a2 = a2;
    }

    public String getA3() {
        return this.a3;
    }
    
    public void setA3(String a3) {
        this.a3 = a3;
    }

    public String getA4() {
        return this.a4;
    }
    
    public void setA4(String a4) {
        this.a4 = a4;
    }

    public String getA5() {
        return this.a5;
    }
    
    public void setA5(String a5) {
        this.a5 = a5;
    }

    public String getA6() {
        return this.a6;
    }
    
    public void setA6(String a6) {
        this.a6 = a6;
    }

    public String getA7() {
        return this.a7;
    }
    
    public void setA7(String a7) {
        this.a7 = a7;
    }

    public String getA8() {
        return this.a8;
    }
    
    public void setA8(String a8) {
        this.a8 = a8;
    }

    public String getA9() {
        return this.a9;
    }
    
    public void setA9(String a9) {
        this.a9 = a9;
    }

    public String getA10() {
        return this.a10;
    }
    
    public void setA10(String a10) {
        this.a10 = a10;
    }

    public String getA11() {
        return this.a11;
    }
    
    public void setA11(String a11) {
        this.a11 = a11;
    }

    public String getA12() {
        return this.a12;
    }
    
    public void setA12(String a12) {
        this.a12 = a12;
    }

    public String getA13() {
        return this.a13;
    }
    
    public void setA13(String a13) {
        this.a13 = a13;
    }

    public String getA14() {
        return this.a14;
    }
    
    public void setA14(String a14) {
        this.a14 = a14;
    }

    public String getA15() {
        return this.a15;
    }
    
    public void setA15(String a15) {
        this.a15 = a15;
    }

    public String getA16() {
        return this.a16;
    }
    
    public void setA16(String a16) {
        this.a16 = a16;
    }

    public String getA17() {
        return this.a17;
    }
    
    public void setA17(String a17) {
        this.a17 = a17;
    }

    public String getA18() {
        return this.a18;
    }
    
    public void setA18(String a18) {
        this.a18 = a18;
    }

    public String getA19() {
        return this.a19;
    }
    
    public void setA19(String a19) {
        this.a19 = a19;
    }

    public String getA20() {
        return this.a20;
    }
    
    public void setA20(String a20) {
        this.a20 = a20;
    }
   








}