package com.bhz.pojo;



/**
 * TbDesignPhbmerge generated by MyEclipse - Hibernate Tools
 */

public class TbDesignPhbmerge  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bdCode;
     private String bhzCode;
     private String intensityGrade;
     private String mergeValue;
     private String mergeName;
     private Integer orderNum;
     private String ext1;
     private String ext2;


    // Constructors

    /** default constructor */
    public TbDesignPhbmerge() {
    }

    
    /** full constructor */
    public TbDesignPhbmerge(String bdCode, String bhzCode, String intensityGrade, String mergeValue, String mergeName, Integer orderNum, String ext1, String ext2) {
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.intensityGrade = intensityGrade;
        this.mergeValue = mergeValue;
        this.mergeName = mergeName;
        this.orderNum = orderNum;
        this.ext1 = ext1;
        this.ext2 = ext2;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getBhzCode() {
        return this.bhzCode;
    }
    
    public void setBhzCode(String bhzCode) {
        this.bhzCode = bhzCode;
    }

    public String getIntensityGrade() {
        return this.intensityGrade;
    }
    
    public void setIntensityGrade(String intensityGrade) {
        this.intensityGrade = intensityGrade;
    }

    public String getMergeValue() {
        return this.mergeValue;
    }
    
    public void setMergeValue(String mergeValue) {
        this.mergeValue = mergeValue;
    }

    public String getMergeName() {
        return this.mergeName;
    }
    
    public void setMergeName(String mergeName) {
        this.mergeName = mergeName;
    }

    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
   








}