package com.bhz.pojo;



/**
 * TbParamSet generated by MyEclipse - Hibernate Tools
 */

public class TbIntensityGrade  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bdCode;
     private String bhzCode;
     private String intensityGrade;


    // Constructors

	/** default constructor */
    public TbIntensityGrade() {
    }

    
    /** full constructor */
    public TbIntensityGrade(String bdCode,String bhzCode,String intensityGrade) {
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.intensityGrade = intensityGrade;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


	public String getBdCode() {
		return bdCode;
	}


	public void setBdCode(String bdCode) {
		this.bdCode = bdCode;
	}


	public String getBhzCode() {
		return bhzCode;
	}


	public void setBhzCode(String bhzCode) {
		this.bhzCode = bhzCode;
	}
   
	
    public String getIntensityGrade() {
		return intensityGrade;
	}


	public void setIntensityGrade(String intensityGrade) {
		this.intensityGrade = intensityGrade;
	}
	
	

}