package com.bhz.pojo;



/**
 * TbMessgeSendType generated by MyEclipse Persistence Tools
 */

public class TbMessgeSendType  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String groupId;
     private String bdCode;
     private String bhzCode;
     private String bhzCarOrder;
     private String sendType;


    // Constructors

    /** default constructor */
    public TbMessgeSendType() {
    }

    
    /** full constructor */
    public TbMessgeSendType(String groupId, String bdCode, String bhzCode, String sendType) {
        this.groupId = groupId;
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.sendType = sendType;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getBhzCode() {
        return this.bhzCode;
    }
    
    public void setBhzCode(String bhzCode) {
        this.bhzCode = bhzCode;
    }

    public String getBhzCarOrder() {
		return bhzCarOrder;
	}


	public void setBhzCarOrder(String bhzCarOrder) {
		this.bhzCarOrder = bhzCarOrder;
	}


	public String getSendType() {
        return this.sendType;
    }
    
    public void setSendType(String sendType) {
        this.sendType = sendType;
    }

}