package com.bhz.pojo;



/**
 * TbMessageUser generated by MyEclipse - Hibernate Tools
 */

public class TbMessageUser  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bdCode;
     private String realName;
     private String telphone;
     private String address;
     private String ext1;


    // Constructors

    /** default constructor */
    public TbMessageUser() {
    }

    
    /** full constructor */
    public TbMessageUser(String bdCode, String realName, String telphone, String address, String ext1) {
        this.bdCode = bdCode;
        this.realName = realName;
        this.telphone = telphone;
        this.address = address;
        this.ext1 = ext1;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getRealName() {
        return this.realName;
    }
    
    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getTelphone() {
        return this.telphone;
    }
    
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
   








}