package com.bhz.pojo;



/**
 * TbParamSet generated by MyEclipse - Hibernate Tools
 */

public class TbParamSet  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bdCode;
     private String bhzCode;
     private String pname;
     private String pvalue;
     private String flag;
     private String remark;


    // Constructors

    /** default constructor */
    public TbParamSet() {
    }

    
    /** full constructor */
    public TbParamSet(String bdCode,String bhzCode,String pname, String pvalue, String flag, String remark) {
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
    	this.pname = pname;
        this.pvalue = pvalue;
        this.flag = flag;
        this.remark = remark;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }

    public String getPvalue() {
        return this.pvalue;
    }
    
    public void setPvalue(String pvalue) {
        this.pvalue = pvalue;
    }

    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }


	public String getBdCode() {
		return bdCode;
	}


	public void setBdCode(String bdCode) {
		this.bdCode = bdCode;
	}


	public String getBhzCode() {
		return bhzCode;
	}


	public void setBhzCode(String bhzCode) {
		this.bhzCode = bhzCode;
	}
   








}