package com.bhz.pojo;

import java.util.Date;


/**
 * TbSignIn generated by MyEclipse - Hibernate Tools
 */

public class TbSignIn  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bdCode;
     private String bhzCode;
     private Date signInDate;
     private String signInUser;
     private String status;


    // Constructors

    /** default constructor */
    public TbSignIn() {
    }

    
    /** full constructor */
    public TbSignIn(String bdCode, String bhzCode, Date signInDate, String signInUser, String status) {
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.signInDate = signInDate;
        this.signInUser = signInUser;
        this.status = status;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getBhzCode() {
        return this.bhzCode;
    }
    
    public void setBhzCode(String bhzCode) {
        this.bhzCode = bhzCode;
    }

    public Date getSignInDate() {
        return this.signInDate;
    }
    
    public void setSignInDate(Date signInDate) {
        this.signInDate = signInDate;
    }

    public String getSignInUser() {
        return this.signInUser;
    }
    
    public void setSignInUser(String signInUser) {
        this.signInUser = signInUser;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   








}