package com.bhz.pojo;



/**
 * TdMergeColsOrder generated by MyEclipse - Hibernate Tools
 */

public class TdMergeColsOrder  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bdCode;
     private String bhzCode;
     private String mergeCols;
     private String mergeColsName;
     private Integer orderNum;
     private String ext1;
     private String ext2;


    // Constructors

    /** default constructor */
    public TdMergeColsOrder() {
    }

	/** minimal constructor */
    public TdMergeColsOrder(String bdCode, String bhzCode, String mergeCols) {
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.mergeCols = mergeCols;
    }
    
    /** full constructor */
    public TdMergeColsOrder(String bdCode, String bhzCode, String mergeCols, String mergeColsName, Integer orderNum, String ext1, String ext2) {
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.mergeCols = mergeCols;
        this.mergeColsName = mergeColsName;
        this.orderNum = orderNum;
        this.ext1 = ext1;
        this.ext2 = ext2;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getBhzCode() {
        return this.bhzCode;
    }
    
    public void setBhzCode(String bhzCode) {
        this.bhzCode = bhzCode;
    }

    public String getMergeCols() {
        return this.mergeCols;
    }
    
    public void setMergeCols(String mergeCols) {
        this.mergeCols = mergeCols;
    }

    public String getMergeColsName() {
        return this.mergeColsName;
    }
    
    public void setMergeColsName(String mergeColsName) {
        this.mergeColsName = mergeColsName;
    }

    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
   








}