package com.bhz.pojo;



/**
 * UserInfo generated by MyEclipse - Hibernate Tools
 */

public class UserInfo  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String username;
     private String userpwd;
     private String bdCode;
     private String bhzCode;
     private String ext1;
     private String ext2;


    // Constructors

    /** default constructor */
    public UserInfo() {
    }

    
    /** full constructor */
    public UserInfo(String username, String userpwd, String bdCode, String bhzCode, String ext1, String ext2) {
        this.username = username;
        this.userpwd = userpwd;
        this.bdCode = bdCode;
        this.bhzCode = bhzCode;
        this.ext1 = ext1;
        this.ext2 = ext2;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserpwd() {
        return this.userpwd;
    }
    
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }


	public String getBhzCode() {
		return bhzCode;
	}


	public void setBhzCode(String bhzCode) {
		this.bhzCode = bhzCode;
	}
   








}