package com.bhz.pojo;



/**
 * UserAuthorityInfo generated by MyEclipse - Hibernate Tools
 */

public class UserAuthorityInfo  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String userName;
     private String funCode;
     private String authValue;
     private String projectId;
     private String ext1;
     private String ext2;


    // Constructors

    /** default constructor */
    public UserAuthorityInfo() {
    }

	/** minimal constructor */
    public UserAuthorityInfo(String userName) {
        this.userName = userName;
    }
    
    /** full constructor */
    public UserAuthorityInfo(String userName, String funCode, String authValue, String projectId, String ext1, String ext2) {
        this.userName = userName;
        this.funCode = funCode;
        this.authValue = authValue;
        this.projectId = projectId;
        this.ext1 = ext1;
        this.ext2 = ext2;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFunCode() {
        return this.funCode;
    }
    
    public void setFunCode(String funCode) {
        this.funCode = funCode;
    }

    public String getAuthValue() {
        return this.authValue;
    }
    
    public void setAuthValue(String authValue) {
        this.authValue = authValue;
    }

    public String getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
   








}