package com.bhz.pojo;



/**
 * UserAuthority generated by MyEclipse - Hibernate Tools
 */

public class UserAuthority  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String userName;
     private String funCode;
     private String authValue;
     private Integer projectId;
     private String sectionId;


    // Constructors

    /** default constructor */
    public UserAuthority() {
    }

	/** minimal constructor */
    public UserAuthority(String userName) {
        this.userName = userName;
    }
    
    /** full constructor */
    public UserAuthority(String userName, String funCode, String authValue) {
        this.userName = userName;
        this.funCode = funCode;
        this.authValue = authValue;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFunCode() {
        return this.funCode;
    }
    
    public void setFunCode(String funCode) {
        this.funCode = funCode;
    }

    public String getAuthValue() {
        return this.authValue;
    }
    
    public void setAuthValue(String authValue) {
        this.authValue = authValue;
    }

	public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public String getSectionId() {
		return sectionId;
	}

	public void setSectionId(String sectionId) {
		this.sectionId = sectionId;
	}
   








}